### ISSUE TITLE
Post Deliverable

### ISSUE THREAD

**Issue by reachguy** [B2G7M/simple-chat-app#6]
# Progress
- [x] Paper Wireframes
  - [x] 404 page
  - [x] Chat (main) page
  - [x] Members List
  - [x] Notifications
    - [x] Joined
    - [x] Left
- [ ] Interactive Wireframes
  - [ ] 404 page
  - [ ] Chat (main) page
  - [ ] Members List
  - [ ] Notifications
    - [ ] Joined
    - [ ] Left
- [ ] Complete Project
  - [ ] 404 page
  - [ ] Chat (main) page
  - [ ] Members List
  - [ ] Notifications
    - [ ] Joined
    - [ ] Left

# Issues
Completed: - 
[x] Paper Wireframes
  - [x] 404 page
  - [x] Chat (main) page
  - [x] Members List
  - [x] Notifications
    - [x] Joined
    - [x] Left

# Positives :+1:

+ We had good communication between team members constantly.
+ We have a clear understanding of our project intentions 
+ We are all following through with our assigned tasks

# Improvements :star:

+ We need to start getting more excited about coding the actual thing
+ We will be meeting in person to work collaboratively to avoid confusion when we start this week
+ We need to constantly be asking ourselves if our actions are aligning with our intentions

# Request for Feedback :ear:
+ A step by step guide on how to actually start/set up the project would be really helpful (hey, that's not feedback!)
+ Feedback was provided on the realistic possibility of being able to have a selection of avatars. We found the solution went against our project intention, so we are dropping it.

**Comment by B2G7M** [comment]
@ericadamski

**Comment by ericadamski** [comment]
⭐️ We need to constantly be asking ourselves if our actions are aligning with our intentions :star:
